- proposals/gc/Overview.md
This is a brain dump capturing various previous discussions and some of my notes. Lots more to be said and discussed, obviously, but we have to start somewhere.
> Initial overview

- proposals/gc/Overview.md
Also, remove the future idea of primitive closure support.  Choosing
the representation of a closure is part of the domain of the compiler
that targets WebAssembly; WebAssembly can just provide the primitives to
support the choices that a compiler would like to make.
> Eliminate second allocation in closure example

- proposals/gc/Overview.md
Made a pass through the overview section, removing the use of "tuple" and using "length" for arrays instead of "size", as well as small fixes elsewhere.
> Minor fixes and rewordings

- proposals/gc/MVP.md
- proposals/gc/Overview.md
A more concrete suggestion for an MVP feature set. Still a number of todos, and instruction names diverged from Overview, should fix.
@lukewagner, WDYT?
> First go at MVP proposal

- proposals/gc/MVP.md
- proposals/gc/Overview.md
This came out of the discussion on PR #34.
Also, add more motivating explanation in overview.
> Add explicit RTT support for casts

- proposals/gc/MVP.md
- proposals/gc/Overview.md
This adds:
* the `ref.test` instruction that tests a reference's RTT without actually casting;
* the `optref.as_nonnull` and `br_on_null` instructions that null-check and convert an optref to a ref. This is no longer subsumed by casts, because they cannot be used if the object has no RTT attached;
* the `rtt.i31ref` instruction, which was missing before;
* more compact shorthands `ref.is_func`, `ref.as_func`, `ref.is_i31`, `ref.as_i31`.
I'm somewhat undecided on the shorthands, but wanted to throw them out there for discussion.
> Additional conversion instructions

- proposals/gc/MVP.md
Instead of using `<reftype>` as immediates, which was a bit of a categroy error, introduce `typeuse`, which denotes either a user-defined type (via a type index) or a predefined type (via direct opcode).
> Distinguish typeuse from reftype

- proposals/gc/MVP-JS.md
- proposals/gc/MVP.md
This PR moves the stub "JS API" section out of MVP.md into a new MVP-JS.md that defines the JS API in terms of the [JS Typed Objects proposal](https://github.com/tschneidereit/proposal-typed-objects/blob/master/explainer.md).
> Describe JS API for GC

- proposals/gc/Charter.md
C+P courtesy of the [WASI charter](https://github.com/WebAssembly/WASI/blob/master/Charter.md).
> Add charter for GC subgroup

- proposals/gc/MVP.md
Following implementation feedback from @lukewagner, @jakobkummerow, and @tebbi, includes the following changes:
* RTT types include a natural number tracking their inheritance depth, in order to _actually_ enable efficient casts.
* Disallow `struct/array.new` to take a super-RTT, in order to allow direct representation of RTTs as map/shape objects without hidden dynamic allocation. We could still provide partial type hiding via another RTT allocation instruction, but that can be deferred.
* Fully type-annotate RTT-related instructions for now.
* Renamed `constype` to `heaptype`, as in funcref repo.
More to come...
> More clarifications and tweaks

- proposals/gc/MVP.md
- proposals/gc/Overview.md
- proposals/gc/Post-MVP.md
A somewhat more complete and detailed write-up of post-MVP features, and rationale why they are not included in the proposed MVP. It is intended to clarify some reoccurring questions and suggestions about the proposal. Probably not a comprehensive list yet, but making progress. :)
> List and describe post-MVP features in more detail

- proposals/gc/MVP.md
- proposals/gc/Post-MVP.md
Following a recent discussion with @jakobkummerow and @tebbi, this PR suggests a simplification to the semantics of RTTs and casts: instead of representing arbitrary heap types, RTTs only denote *concrete* types, making casts simpler and more uniform.
Previously, an RTT could represent an arbitrary heap type, including abstract types like `anyref` or `funcref`. Such RTTs could also be used as targets of a cast. Consequently, casts were a complex operation that could involve multiple steps, the number and details of which differ by source/target type. For example, to cast from `anyref` to `(ref $t)`, where `$t` is a struct, the operational semantics of `ref.cast` would need to
(1) check that the reference isn’t null or a scalar;
(2) check that it points to a struct;
(3) do the actual check …
> Simplify RTTs and decompose casts

- proposals/gc/MVP.md
This changes `ref.cast` to propagate null instead of trapping. Addresses #152.
(For now, not introducing two variants of the instruction -- let's see how common the other case really is to justify duplication.)
> Make ref.cast succeed on null

- proposals/gc/Overview.md
Are arrays of length 0 possible?
> Fix possible typos

- proposals/gc/Overview.md
Updating the links in the overview to reflect the move of the section on parametric polymorphism to the Post-MVP.
> Fix links to type parameters

- proposals/gc/Overview.md
Engines cannot flatten a struct with an immutable i32 because all `data` references in the current MVP have identity (via reference equality), which flattening does not preserve.
> Remove flattening statement about i32ref

- proposals/gc/MVP.md
> Relax typing of classification instructions; opcode for dataref

- proposals/gc/MVP.md
Fixes inconsistency with `br_on_null`, as [pointed out](https://github.com/WebAssembly/function-references/issues/45#issuecomment-772678955) by @kripken.
> Allow extra args on branches

- interpreter/binary/decode.ml
- interpreter/binary/encode.ml
- interpreter/script/js.ml
- interpreter/syntax/free.ml
- interpreter/syntax/types.ml
- interpreter/text/arrange.ml
- interpreter/text/lexer.mll
- interpreter/text/parser.mly
- interpreter/valid/match.ml
- interpreter/valid/valid.ml
- test/core/array.wast
- test/core/struct.wast
This extends the interpreter with all the added type structure from the proposal, i.e., type en/decoding, text parsing/printing, validation of type definitions, etc. Includes a few simple tests for type definitions.
Instructions to follow.
> [interpreter] Implement types

- proposals/gc/MVP.md
As a result of the discussion on WebAssembly/function-references#45, this adds inverse versions of the `br_on_*` and `br_cast` instructions as well.
> Add negated versions of br_on_* instructions

- interpreter/binary/decode.ml
`E8` was decoded as `(ref null (rtt ...))` but should be `(ref (rtt ...))`.
> Fix nullability in decoding of rtt ref

- proposals/gc/MVP.md
- proposals/gc/Post-MVP.md
Addresses #260, following the V8 prototype spec, by adding:
* `array.new_data`
* `array.new_elem`
* `array.new_fixed`
Also adds additional bulk operators to Post-MVP doc.
Instruction names differ from V8 doc to clarify where allocation happens and for consistency with memory and table instructions.
Moreover, make all `*.new` instructions constant, except `array.new_elem`.
> Add bulk array creation instructions

- proposals/gc/MVP.md
Fixes mostly minor typos with no semantic effect, except for a case in the subtyping rules where I think `$t'' <: $t` should actually be `$t'' <: $t'`.
> Fix a few typos in the MVP explainer

- test/core/gc/type-subtyping.wast
This PR adds additional tests for declarations that attempt to define structs, arrays, and function types that have invalid subtyping relations.
> Additional negative subtyping tests

- interpreter/host/env.ml
- interpreter/host/spectest.ml
- interpreter/runtime/instance.ml
- interpreter/script/js.ml
- interpreter/syntax/ast.ml
- interpreter/syntax/types.ml
- interpreter/valid/match.ml
- interpreter/valid/valid.ml
- proposals/gc/MVP.md
- test/core/type-rec.wast
Correct typing of functions in context and external types to track vars instead of expanded function types, so that iso-recursive equality is preserved.
Adds tests as well.
Fixes #290.
> Fix handling of recursive function types

- interpreter/binary/decode.ml
- interpreter/binary/encode.ml
- interpreter/script/js.ml
- interpreter/syntax/free.ml
- interpreter/syntax/types.ml
- interpreter/text/lexer.mll
- interpreter/text/parser.mly
- interpreter/valid/match.ml
- interpreter/valid/valid.ml
- proposals/gc/MVP.md
- test/core/ref_null.wast
Bring back the nullref type.
- In binary, it's a heaptype encoded as -0x12 (previously used for anyref, now unused).
- In text, `nullref` is shorthand for `(ref null none)`, where `none` is the name for the bottom heap type (chosen as opposite to `any`).
No changes needed to the interpreter other than supporting it in binary and text format and allowing it in the validator. The rest of the change is merely renaming and reordering.
> Add nullref

- proposals/gc/Post-MVP.md
Concretize the argument that implicit RTTs would have unnecessary overhead by providing an example use case, generic containers, that would not need RTTs.
> Add example for RTTs + generics

- proposals/gc/Post-MVP.md
And document the potential performance benefits we've measured.
> Add method dispatch as a post-MVP feature

- proposals/gc/Post-MVP.md
Explain that casting should not change even if we make RTTs more expressive as meta objects in the future.
> Add details on post-MVP RTTs with static fields

- proposals/gc/MVP.md
Adds missing label index for new branch instructions in documentation.
> Add labels for `br_on[_non]`

- proposals/gc/MVP.md
Addresses #274.
This PR modifies the MVP doc to replace the existing classification and cast instructions with casts that can target any reference type:
```
ref.test null? <heaptype>
ref.cast null? <heaptype>
br_on_cast $l null? <heaptype>
br_on_cast_fail $l null? <heaptype>
```
The typing rules for these casts become somewhat complex, in order (1) to make sure that source and target type are in the same hierarchy, and (2) to handle the propagation and negation of the optional `null` attributes correctly.
Furthermore, the PR repurposes the `dataref` type as `structref`. The main purpose of `data` was to denote the required source type for concrete casts. Since that requirement is gone, so is the purpose. For the remaining use cases, `struct` is typically more precise. That also avoids …
> Refactor casts

- proposals/gc/MVP.md
Add an explicit note pointing out that the number of entries is the number of rec groups rather than the number of types, which followed from the existing text but was counterintuitive and easy to miss.
Fixes #327.
> Clarify that type section entries are rec groups

- proposals/gc/Post-MVP.md
Summarizing these post-MVP ideas in the documentation will allow us to close out their corresponding issues.
Closes #208.
Closes #239.
> Add throwing instructions and funcref equality to Post-MVP

- interpreter/syntax/types.ml
- interpreter/valid/valid.ml
- proposals/gc/MVP.md
- test/core/gc/br_on_cast.wast
- test/core/gc/br_on_cast_fail.wast
Address #342 and simplify rules on the way. Also adjust interpreter and add tests.
@Liedtke, PTAL.
> Relax nullability for br_on_cast

- .github/workflows/main.yml
- interpreter/binary/decode.ml
- interpreter/binary/encode.ml
- interpreter/exec/eval.ml
- interpreter/host/spectest.ml
- interpreter/script/js.ml
- interpreter/syntax/free.ml
- interpreter/syntax/types.ml
- interpreter/text/arrange.ml
- interpreter/text/lexer.mll
- interpreter/text/parser.mly
- interpreter/valid/match.ml
- interpreter/valid/valid.ml
- proposals/gc/MVP.md
- test/core/gc/br_on_cast.wast
- test/core/gc/br_on_cast_fail.wast
- test/core/gc/ref_cast.wast
- test/core/gc/ref_eq.wast
- test/core/gc/ref_test.wast
- test/core/gc/type-subtyping.wast
This adds a spec of the final attribute for experimentation:
* In the abstract syntax, it is possible to write `sub $t* ...` or `sub final $t* ...`.
* In the binary format, `sub final` is encoded as `-0x32`, with the same format as `sub`.
* When validating a `sub` definition, none of the supertypes may be final.
* The non-sub shorthands (and therefor existing function types) are reinterpreted to `final`.
Due to the latter, a subtypable struct or array must now be written explicitly, with an empty list of supertypes:
```
(type (struct))  ;; final, no supertypes (shorthand)
(type (sub final (struct)))  ;; same in expanded form
(type (sub (struct)))  ;; non-final, no supertypes
(type (sub $t (struct)))  ;; non-final, with supertype
(type (sub final $t (struct)))  ;; final, with supertype
```
> Add `final` attribute

- proposals/gc/MVP.md
This is a minor PR to sync the description of constant expressions in the proposal document (it's missing `extern.internalize/externalize`).
> Sync constant expression descriptions

- document/js-api/index.bs
This PR adds formal JS API spec text based on the "no-frills" proposal in https://github.com/WebAssembly/gc/issues/279 and https://docs.google.com/document/d/17hCQXOyeSgogpJ0I0wir4LRmdvu4l7Oca6e1NkbVN8M/.
I've also opened an issue to discuss certain aspects of this PR: https://github.com/WebAssembly/gc/issues/353
> [spec] Initial JS API formal spec for the GC proposal

- document/js-api/index.bs
- proposals/gc/MVP-JS.md
- proposals/gc/MVP.md
Based on discussion in #335 and subgroup meetings.
Closes #335.
> Document new implementation-defined limits

- proposals/gc/MVP-JS.md
We had a TODO to ensure bidirectional identity preservation in the JS spec, but
in fact we already do that, so remove the TODO and replace it with a desciption
of the mechanism we use.
> Replace TODO in MVP-JS.md

- document/core/syntax/instructions.rst
- document/core/syntax/types.rst
- document/core/util/macros.def
- proposals/gc/MVP.md
Does not yet include type definitions.
> Spec abstract syntax for GC types and instructions

- proposals/gc/MVP.md
Add descriptions of array.fill, array.copy, array.init_elem, and
array.init_data to MVP.md.
> Add bulk array instructions to MVP.md

- document/core/exec/instructions.rst
- document/core/exec/values.rst
Leaving out type unrolling for now, since that's defined in #377.
> Prose for basic struct/array instructions

- proposals/gc/MVP.md
This adds the bulk array instructions to the instruction list in the binary format of the MVP markdown.
> Add array instructions to MVP

- interpreter/script/js.ml
Should fix issues listed in #396.
Right now, JS-converted tests cannot distinguish ref.array and ref.struct results. But there are only 4 tests doing this, and they are fairly trivial, so that imprecision should be fine for now. (We already have a similar imprecision with tests inspecting NaN results.)
> Fix JS conversion

- document/core/exec/runtime.rst
- document/core/util/macros.def
Having I8.PACK and I16.PACK in sans serif was visually very jarring and felt
inconsistent with other similar values in the spec. Change these to lowercase
for consistency and to make it look much better.
> Make type setting of i8.pack and i16.pack less jarring

- document/core/exec/instructions.rst
Fix links from the execution prose to the incorrect validation rules and add
missing links.
> Fix links to validation from exec spec

- document/core/exec/instructions.rst
Consistently use `\X{ft}^n` to refer to the struct field types in the execution
rules for struct.get and struct.set.
Fixes #400.
> Fix mixed use of ft^\ast and ft^n in struct.get/set execution

- document/core/exec/instructions.rst
Many of the new GC instructions used metavariables like `\typeidx` and
`\dataidx` in their prose, but `x` and `y` in their formalisms. To make the
prose and formalisms more consistent, and for consistency with the metavariables
used for other pre-existing instructions, use the `x` and `y` metavariables
everywhere.
> Make metavariables used in execution spec more consistent

- document/core/exec/instructions.rst
Add execution prose for array.fill, array.copy, array.init_data, and
array.init_elem. As a drive by consistency fix, also remove unnecessary
parentheses around values in the prose for other GC instructions. These
parentheses do not appear in the prose for any other instruction.
> Execution prose for bulk array operations

- document/core/valid/matching.rst
This fixes a typo where `func` should be `struct`.
> Fix typo for deftype struct matching

- document/core/appendix/index-types.rst
- document/core/binary/types.rst
- interpreter/binary/decode.ml
- interpreter/binary/encode.ml
- test/core/gc/binary-gc.wast
> Updated packed type encodings in the spec and interpreter

- document/core/exec/instructions.rst
- document/core/syntax/instructions.rst
- document/core/util/macros.def
Previously the array.copy semantics were defined in terms of executing array.get
on the source array, which is not correct if the source array contains a packed
type. Update the semantics prose and formalism to choose between array.get and
array.get_u depending on whether the array contents are packed. The interpreter
does not need updating because it already handled the difference correctly.
> Update array.copy semantics to handle packed types

- test/core/gc/struct.wast
I noticed there weren't many tests for packed struct operations, and none for `struct.get_u`. This patch adds some more tests in `struct.wast` for those cases.
> [test] Add tests for packed struct fields

- document/core/exec/modules.rst
- document/core/util/macros.def
- document/core/valid/modules.rst
- test/core/global.wast
Also, add a couple of respective test cases.
> Spec sequential visibility for globals

- test/core/gc/br_on_cast.wast
- test/core/gc/br_on_cast_fail.wast
Add tests checking for validation failures if the output type of br_on_cast or
br_on_cast_fail is not a subtype of the input type.
> Test that br_on_cast{_fail} must do a down cast

- document/core/text/types.rst
When referring to the `rec` keyword, do not link to the abstract syntax that
happens to have the same name. Fix suggested by @bvisness and split out from
https://github.com/WebAssembly/gc/pull/413.
Do not link to the abstract syntax
> Remove incorrect link to abstract syntax

- document/core/text/modules.rst
- document/core/text/types.rst
- document/core/util/macros.def
Since a deftype is already something else outside the text format. Also fix an
abbreviation to correctly use "typedef" instead of "subtype". Adapted from a fix
by @bvisness in #413.
> Rename text "deftype" to "typedef"

- document/core/exec/instructions.rst
- document/core/valid/instructions.rst
Add side conditions on ref.test/ref.cast rules that check that the RHS type is well-formed before invoking subtyping.
@conrad-watt, PTAL
> [spec] Add missing side conditions

- document/core/valid/modules.rst
- interpreter/valid/valid.ml
- test/core/global.wast
> Fix context for table initialisers

- document/core/appendix/implementation.rst
Noticed that we still needed to extend those bullet lists in the appendix.
> List possible implementation limits

- document/js-api/index.bs
As per [discussion](https://github.com/WebAssembly/gc/pull/439#discussion_r1332282446).
@takikawa, PTAL. Reordered slightly to make it clearer.
> [js-api] Allow exported funcs as any

- test/js-api/gc/exported-object.tentative.any.js
- test/js-api/wasm-module-builder.js
Adds tests for the "Exported GC Object" described in the proposed JS API spec in https://github.com/WebAssembly/gc/pull/352.
This requires updating the wasm module builder helper library, which is now fairly de-synced with the V8 library it's based on. I've only synced a bare minimum in this PR to be able to construct some GC modules (syncing the whole thing causes other tests to fail).
The V8 version also uses a slightly different opcode numbering than the current spec document in this repo. In this PR I went with the spec numbering (in the end they will all need to be synchronized).
This doesn't have tests for all the ToWasmValue/ToJSValue cases for conversions, which would also be useful to add.
> [test] Add tentative JS API tests for Exported GC Object

- test/js-api/gc/i31.tentative.any.js
- test/js-api/instanceTestFactory.js
- test/js-api/module/exports.any.js
- test/js-api/wasm-module-builder.js
This PR builds on #355 (included in the first commit) to add tests for I31 refs in the JS API. It should be merged after #355.
It adds tests for i31refs passed to wasm from JS, JS from wasm, and testing that numbers in i31 range are i31refs and not hostrefs (and that others are hostrefs).
I've tested this on V8 (wasm-js tests), Firefox (WPT tests with final opcode patches merged), and WebKit (WPT tests, with some bug fixes that aren't yet upstream, plus a final opcode patch).
> [test] Add JS API tests for I31 refs

- test/js-api/gc/casts.tentative.any.js
This PR adds JS API tests for exercising `ToWebAssemblyValue` with all the categories of GC types. It adds on top of the previous two JS API tests PRs, so it should be merged after them (just the last commit is new).
With these three tests, I think we will have good test coverage of the JS API, but if anyone sees any missing cases that should be covered that would be helpful to know.
The tests pass on JSC (w/ some unlanded patches), V8, and SpiderMonkey (w/ final opcodes) with one exception that I'll comment below.
> [test] Add boundary cast tests for ToWebAssemblyValue

- test/core/gc/type-subtyping.wast
- test/core/type-equivalence.wast
Such as the `register` commands in [linking.wast](https://github.com/WebAssembly/gc/blob/main/test/core/linking.wast), I think it's better to prevent from the module name conflict for each `register` commands in a `wast` file.
> [test] Prevent from module name conflict when registering in wast.

- document/core/exec/instructions.rst
Hello,
This pull request fixes some minor errors in the specification for execution of `struct.new`, `array.new_fixed` and `br_on_cast(_fail)` instructions.
1. Change the last `Return ...` in prose notation specification into `Push ... to the stack` for both `new` instructions.
2. Change `array ft^n` in formal notation specification into `array ft` for `array.new_fixed` instruction.
3. Add the frame `F` in the reduction rule of `br_on_cast(_fail)`, as `F` is used in the auxiliary function `clos`.
4. Fix typo: `X{rt}_2` ~> `\X{rt}_2`for `br_on_cast(_fail)` instructions.
> [spec] Fix spec for execution of `struct.new`, `array.new_fixed` and `br_on_cast(_fail)`

- document/core/exec/values.rst
- document/core/syntax/types.rst
- document/core/valid/conventions.rst
- document/core/valid/instructions.rst
- document/core/valid/modules.rst
Adjust various places that were still using a functype or a typeidx instead of a deftype to type functions. Also, add missing subsumtion for external values and reference values.
@q82419, please take a look.
> [spec] Fix typing of functions

- document/core/valid/instructions.rst
The `array.set` has no `i` immediate.
> [spec] fix immediate of `array.set` instruction.

- document/core/exec/instructions.rst
Trap case of `array.get` and `array.set` is omitted or wrongly described.
* Current specification
* Suggested change
> Fix `array.get/set` reduction rule

- document/core/exec/instructions.rst
As far as I know, `array.get` instruction requires a type index, so type index should be passed to `getfield` function.
* Current specification
* Suggested change
> Pass index argument to `getfield` function

- document/core/exec/instructions.rst
I fixed OOB cases for `array.get/set`.
> Fix OOB cases for `array.get/set`

- test/core/gc/ref_test.wast
This PR adds `assert_return` around the invocations of two test functions at the end of `gc/ref_test.wast`
> [test] Add `assert_return`

- document/js-api/index.bs
Handle the case where the global has a reference type. See #461.
> [js-api] Update the 'read the imports' process

- document/js-api/index.bs
- proposals/gc/MVP-JS.md
- proposals/gc/MVP.md
The new limits were previously merged in #360, but apparently that PR was to another branch that itself was never merged. Reland that change with two additional fixes:
- Add digit separators in the numbers to improve readability and match the formatting of other limits.
- Add an explicit limit of 1,000,000 types per recursion group. This is not intended to be a functional change, but this limit was previously left implicit.
> [js-api] Document the new implementation limits

- document/js-api/index.bs
These were accidentally deleted in #471.
> [js-api] Restore accidentally-deleted digit separators

- document/core/exec/instructions.rst
Hi,
In the `array.set` rule, there is `if expand(F.module.types[x]) = struct ft^n` but it should be `if expand(F.module.types[x]) = array ft`.
> fix rule for array.set

- document/core/text/instructions.rst
- document/core/util/macros.def
The underscore needs to be escaped.
> [spec] Fix formatting of any.convert_extern and extern.convert_any

- document/core/exec/instructions.rst
* Current specification
* Suggested change
Fix index: 15 -> 11
Remove one space in `Trap` statement. (I don't know why, but 4 spaces makes indentation and width weird in `array.new_elem`)
> Minor changes on array.new_elem

- proposals/gc/Overview.md
A couple of the inconsistencies were due to changes in the dependent function-references proposal:
* `optref` seems to have been changed to `ref null` at some point
* the `let` instruction was removed in favour of validation (https://github.com/WebAssembly/function-references/pull/63)
The other couple of inconsistencies just seemed to accidentally referencing the wrong label in an example and description of an example.
> Fix Overview.md inconsistencies

- interpreter/text/parser.mly
It is already defined two lines above. This was introduced in #422.
`ocamlyacc` doesn't produce an error in these cases, but it probably should. I opened [an issue upstream](https://github.com/ocaml/ocaml/issues/12723) .
I tried on the Owi interpreter where I'm using Menhir and it is producing an error when this is the case: `Error: the token REF_I31 has multiple definitions.`.
It would be nice to switch to Menhir at some point (which is the standard in OCaml nowadays) but I guess introducing one more dependency is not acceptable ?
> remove duplicated token definition in parser

- document/core/valid/instructions.rst
Currently the spec has this note:
> Note
>
>Currently, constant expressions occurring in [globals](https://webassembly.github.io/gc/core/syntax/modules.html#syntax-global), [element](https://webassembly.github.io/gc/core/syntax/modules.html#syntax-elem), or [data](https://webassembly.github.io/gc/core/syntax/modules.html#syntax-data) segments are further constrained in that contained instructions are only allowed to refer to imported globals. This is enforced in the [validation rule for modules](https://webassembly.github.io/gc/core/valid/modules.html#valid-module) by constraining the context accordingly.
>
>The definition of constant expression may be extended in future versions of WebAssembly.
https://webassembly.github.io/gc/core/valid/instructions.html#valid-constant
I think this is …
> [spec] Update global.get note on constant expressions

- test/core/gc/binary-gc.wast
This avoids having two binary encoding errors which makes testing that a parser caught the expected error difficult.
@tlively PTAL
> Fix off-by-one length in `binary-gc.wast`

- document/core/exec/instructions.rst
Many prose related to struct and array omit "Let F be ..."
Not only that, `Array.copy` also omit F in the reduction rule.
> Add current frame

- document/core/exec/instructions.rst
- document/core/exec/runtime.rst
This is the semantics of `ref.null ht` in the current specification.
But I think simply pushing `ref.null ht` is problematic.
Consider the following example, which is simplified version of "test-sub" in ref_test.wast.
```
(module
(type $t0 (sub (struct)))
(func (export "test-sub")
;; must hold
(ref.test (ref null $t0) (ref.null $t0))
(drop)))
(assert_return (invoke "test-sub"))
```
According to the semantics of `ref.test`, we first need to get the reference type of `ref.null $t0`.
However, the typeindex `$t0` is not ok under empty context.
In the reference interpreter, type index of `ref.null $t0` is substituted before pushed.
```
let rec step (c : config) : config =
....
| RefNull t, vs' ->
Ref (NullRef (subst_heap_type (subst_of c.frame.inst) t)) :: vs', []
```
Therefore, I fixed the …
> Fix ref.null semantics

- test/core/gc/array.wast
As the trap message in the [interpreter](https://github.com/WebAssembly/gc/blob/main/interpreter/exec/eval.ml#L713).
> [test] Unify the error message of `"null array reference"`.

- test/core/gc/struct.wast
Continue from #487.
Sorry about missing this.
> [test] Unify the error message of `"null structure reference"`.

- test/core/gc/array.wast
Previously `array.get_s` was not exercised by the test suite at all.
`array.wast` exercises `array.get_u` and has been updated to also exercise `array.get_s`.
@tlively PTAL
> Exercise `array.get_s` in `array.wast`

- test/core/br_on_null.wast
- test/core/gc/br_on_cast_fail.wast
> Add a test for #516 to the test suite

- document/core/appendix/embedding.rst
Fixes a minor spacing issue in the following:
(the spacing next to the turnstile)
> [spec] minor formatting adjustment

- document/core/appendix/embedding.rst
- document/js-api/index.bs
- test/js-api/gc/default-value.tentative.any.js
- test/js-api/gc/i31.tentative.any.js
- test/js-api/wasm-module-builder.js
This PR addresses issue #501 and adjust `DefaultValue` in the JS API so that it delegates to a embedder API function in the core spec, with a special case for `externref` to use `undefined`.
Note that for `anyref` and other non-externref types it will use `null` as the default value. For non-null types,  it produces `error` and that is thrown as a `TypeError` for `WebAssembly.Table.prototype.set` and `WebAssembly.Table.prototype.grow`.
Rendered spec change for the core spec:
Rendered change for `DefaultValue` (there are changes to use sites too, not shown):
The PR also adds a new WPT test for the error cases specifically. Both Firefox and Chrome passed the test when I tried it out.
> [js-api][test] Refine DefaultValue for new reference types

- document/js-api/index.bs
Fixes #521. Goes along with #498.
> [js-api] Throw consistent exns in "read the imports"

- proposals/gc/MVP.md
The first argument for `ref.cast` should be a reference type. However, the code example in `MVP.md` seems to have a heaptype.
(Assuming the `$C` is defined as follows based on the context)
```wasm
(module
(type $A (sub (struct)))
(type $B (sub $A (struct (field i32))))
(type $C (sub $B (struct (field i32 i32))))
(func $castBtoC (param $x (ref $B)) (result (ref $C))
(ref.cast $C (local.get $x))
)
)
```
```sh
$ wasm -d test.wat
test.wat:6.15-6.17: syntax error: unexpected token
```
(Where `wasm` is a reference interpreter built from https://github.com/WebAssembly/gc/commit/0ba84fb5f993348fc3eb052968bd869aa7bc3875)
---
Please let me know if I misunderstand something :)
> Fix an example code for ref.cast in MVP.md

- test/core/gc/type-subtyping.wast
Test that validation allows `call_indirect` to have a type immediate that is a supertype of or unrelated to the table element type and that the runtime behavior is correct in these cases.
> [test] Test `call_indirect` subtyping more thoroughly

- document/core/appendix/index-instructions.py
It produces a non-null `(ref i31)` not an `i31ref` aka `(ref null i31)`.
> Fix typing of `ref.i31` in the appendix

- document/core/exec/instructions.rst
The prose incorrectly used "larger than or equal to" when it should have used just "larger than." The formalism was already correct.
Fixes #536.
> [Spec] Fix bounds check prose for array.fill and array.copy

- test/core/gc/i31.wast
Copy-paste bug. Don't repeatedly assert the first element's value, but each element in the table.
> Fix i31.wast default table element assertions

- proposals/gc/Overview.md
The overview currently contains this section (emphasis my own): 
> A runtime type is an expression of type `rtt <type>`, which is another form of opaque value type. It represents the static type `<type>` at runtime.
> In its plain form, a runtime type is obtained using the instruction **`rtt.get`**
> ```
> (rtt.canon <type>)
> ```
I believe that  the text "`rtt.get`" was intended to be replaced by "`rtt.canon`"
> Fixup out of date reference to rtt.get

- document/core/syntax/instructions.rst
According to other places in docs and my research on dumped wat files, I consider that funcidx for this call places on stack, not as parameter.
> Fix `RETURNCALLREF` argument type

- test/core/return_call_ref.wast
The modified test case previously had two errors. Fix the unintentional error, ensuring that the test properly tests the intended error.
> Fix type in return_call_ref.wast

- test/core/gc/array_new_data.wast
I noticed that the existing tests didn't exercise out-of-bounds indexing of the data segment, so I added a test for that.
At the same time, since I was already creating a dedicated `.wast` file for testing `array.new_data`, I also added a few general tests to round the file out. Some of these might technically duplicate things that already happen to be tested in `array.wast`, but I think that's probably fine, and that it is good to have dedicated tests in this new file. I can remove them if we'd rather not have these potential-duplicate tests.
> Expand tests for `array.new_data`

- test/core/gc/array_new_elem.wast
Similar to https://github.com/WebAssembly/gc/pull/562 but for `array.new_elem`.
I opted to exercise both expression-style elements and the old MVP-style function-index elements, as they have slightly different representations in Wasmtime and that means we end up doing the indexing in two different code paths depending on which type of element segment we have. Figured that other engines might have similar code paths so it's good to test both.
> Test out-of-bounds element segment indexing for `array.new_elem`

- test/core/gc/type-subtyping-invalid.wast
Specifically around the requirements that both field types have the same mutability and that the storage type must be exactly the same when the field type is mutable.
@tlively PTAL, thanks!
> Add some tests for invalid subtyping due to non-matching field types
