README.md
Hi, I just found a mistake on README.md while just passing by so fixed it.
Thanks,
Honggyu
=> Fix duplicated 'add's in README.md

proposals/gc/MVP.md
=> Expand explanation of RTTs

proposals/gc/Overview.md
=> Fix a typo in the overview

proposals/gc/Overview.md
=> Fix some out-of-date pieces of overview

proposals/gc/MVP.md
=> Fix def of sub-RTT

interpreter/binary/decode.ml, interpreter/binary/encode.ml, interpreter/exec/eval.ml, interpreter/script/js.ml, interpreter/syntax/ast.ml, interpreter/syntax/free.ml, interpreter/syntax/operators.ml, interpreter/syntax/types.ml, interpreter/text/arrange.ml, interpreter/text/lexer.mll, interpreter/text/parser.mly, interpreter/valid/valid.ml, proposals/gc/MVP.md, test/core/binary.wast, test/core/call_ref.wast, test/core/func_bind.wast, test/core/return_call_ref.wast, test/core/struct.wast
This PR implements GC instruction en/decoding, parsing/printing, & validation. Also adds a few more tests.
With this, the reference interpreter can convert GC stuff between text and binary format and back. (Though test coverage is currently incomplete, so there might be bugs.)
Evaluation is to follow.
=> Implement instructions and validation

interpreter/binary/decode.ml, interpreter/binary/encode.ml, proposals/gc/MVP.md
Changes opcode from -0x20 to -0x1a. Fixes #269.
=> Change arrayref opcode

interpreter/exec/eval.ml, proposals/gc/MVP.md, test/core/gc/i31.wast
=> Handle i31.get on null

proposals/gc/MVP.md
=> Fix initialisation of packed field types

proposals/gc/MVP.md
Now that we're in phase 3, the design should be relatively stable.
=> Remove note about design being in flux

interpreter/text/parser.mly, interpreter/util/lib.ml, interpreter/util/lib.mli, test/core/type-rec.wast
=> Fix handling of recursive types in parser context

proposals/gc/Overview.md
=> Make sure code block is formatted as code in overview

document/core/appendix/properties.rst, document/core/exec/instructions.rst, document/core/exec/runtime.rst, document/core/exec/values.rst, document/core/syntax/instructions.rst, document/core/syntax/modules.rst, document/core/syntax/types.rst, document/core/syntax/values.rst, document/core/text/types.rst, document/core/util/macros.def
First part, still missing most of the prose.
=> Spec execution, part 1

document/core/exec/instructions.rst
Also add some missing frame and store contexts and fix other minor typos.
=> Add null checks to struct and array accessor execution

document/core/exec/instructions.rst, document/core/exec/numerics.rst
See https://github.com/WebAssembly/gc/pull/387#discussion_r1242864600
=> Fix spec.fix-array.new_data

document/js-api/index.bs
Fix #399 and a couple of other small bugs with conversion to/from JS numbers.
=> Fix JS integer conversion

document/core/appendix/index-types.rst, document/core/binary/types.rst
Fix #431.
@jakobkummerow, PTAL.
=> Fix rectype opcodes

proposals/gc/MVP.md
Adds a few missing argument descriptions + fixes syntax.
=> Edit MVP.md parameters column

document/js-api/index.bs
See [comment](https://github.com/WebAssembly/gc/pull/439/files#r1333519677). @takikawa, PTAL.
=> [js-api] Fix type check for externrefs

README.md
Also add a note pointing out that the details in Overview.md are out of date.
=> Update README.md to link to the spec doc

document/core/valid/instructions.rst
=> [spec] Extend definition of constants

document/core/text/modules.rst
=> Add missing init expression to table text format

document/core/valid/types.rst
=> [spec] Fix prose for blocktype validation

document/core/exec/instructions.rst
@jaehyun1ee, please take a look. Fix #476.
=> [spec] Tweak dimensionality in array.new_data

document/core/exec/modules.rst
=> [spec] Sync prose for module instantiation

document/core/valid/matching.rst
=> [spec] Add note about type equivalence

document/core/exec/instructions.rst
Fix #508. Also tweak to be more symmetric to table/memory.init.
=> [spec] Fix prose for bounds check in array.init_data/elem

document/core/appendix/algorithm.rst, document/core/valid/instructions.rst
=> [spec] Add note and algorithmic rules about typing with top type
